#!/usr/bin/perl -w

use KMax;

use UniLang::Agent::Agent;
use UniLang::Util::Message;

$UNIVERSAL::agent = UniLang::Agent::Agent->new
  (Name => "KMax",
   ReceiveHandler => \&Receive);
$UNIVERSAL::app = KMax->new();

sub Receive {
  my %args = @_;
  $UNIVERSAL::app->ProcessMessage
    (Message => $args{Message});
}

$UNIVERSAL::app->Execute();
